# Generated by Django 3.1.14 on 2023-05-15 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.UUIDField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=300)),
                ('created_at', models.TimeField(default=datetime.datetime(2023, 5, 15, 10, 58, 27, 787583, tzinfo=utc))),
                ('create_by', models.EmailField(max_length=200)),
            ],
            options={
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Super_user',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('created_at', models.TimeField(default=datetime.datetime(2023, 5, 15, 10, 58, 27, 829258, tzinfo=utc))),
            ],
            options={
                'db_table': 'Super_user',
            },
        ),
    ]
