# Generated by Django 3.1.14 on 2023-05-15 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 5, 15, 11, 1, 47, 144782, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='super_user',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 5, 15, 11, 1, 47, 178775, tzinfo=utc)),
        ),
    ]
