# Generated by Django 3.1.14 on 2023-05-15 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230515_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 5, 15, 11, 5, 48, 398133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='super_user',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 5, 15, 11, 5, 48, 444730, tzinfo=utc)),
        ),
    ]
