# Generated by Django 3.1.14 on 2023-05-15 11:24

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230515_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('organization_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=400)),
                ('email_id', models.EmailField(max_length=500)),
                ('password', models.CharField(max_length=150)),
                ('user_permission', models.CharField(max_length=50)),
                ('created_at', models.TimeField(default=django.utils.timezone.now)),
                ('created_by', models.EmailField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 5, 15, 11, 24, 19, 39539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='super_user',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 5, 15, 11, 24, 19, 80389, tzinfo=utc)),
        ),
    ]
