# Generated by Django 3.1.14 on 2023-05-15 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20230515_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 5, 15, 11, 25, 14, 421945, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='super_user',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 5, 15, 11, 25, 14, 457187, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
