# Generated by Django 3.1.14 on 2023-05-16 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230515_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_user',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 5, 16, 13, 9, 44, 765369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='super_user',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 5, 16, 13, 9, 44, 802360, tzinfo=utc)),
        ),
    ]
